### ISSUE TITLE
README example doesn't work as expected

### ISSUE THREAD

**Issue by MichaelPGriffin** [jloveric/SentenceSimilarity#14]
Hi @jloveric,

I've followed the example followed in the README and have found that the `similarity` method does not execute to completion.

It looks to me like the issue happens on line 59 of `SentenceSimilarity.js`.

Not sure if either the code or the README would benefit from an edit.  Do you have any interest in this?

-Mike

**Comment by jloveric** [comment]
It could be the problem is that you also need to install "similarity-score".  I've added a mention of that to the readme and updated the packages.  It failed for me (silently) when I wasn't adding that package.

**Comment by MichaelPGriffin** [comment]
Thanks @jloveric  - I can actually rule out the installation of `similarity-score` as a potential cause of the issue, but I am glad you added it to the README 👍🏻

I'm attaching a screenshot of what I see in VS Code. It looks like `options.f` is intended to be a function, but it is an object that contains functions.

![image](https://user-images.githubusercontent.com/20311520/194210966-859585a5-6865-4972-bd92-a99f23f51c73.png)

**Comment by MichaelPGriffin** [comment]
I got a chance to revisit this and figured it out. My problem started with the way I imported `winklerMetaphone`.

I've edited my import statement use a destructuring assignment, and it works as expected.

e.g. `import { winklerMetaphone } from 'similarity-score';`
